### ISSUE TITLE
Question: built-in flash memory size

### ISSUE THREAD

**Issue by lyusupov** [Xinyuan-LilyGO/LilyGO-T-DisplayGD32#1]
According to the schematics, the board uses GD32VF103C**8**T6 variant of GD32V.
Public specs of the C**8** say that is has 64K of flash memory.

Close competitor of the T-Display - Sipeed Longan Nano RISC-V is using  GD32VF103C**B**T6 with 128K of flash memory.

64K flash was Ok 5-6 years ago but it does not seem to be sufficient for most applications these days...
Have you thought about to switch onto C**B** in production T-Display GD32V boards ?

**Comment by lewisxhe** [comment]
Hi,lyusupov
We will add both models, let customers choose the version they need.

**Comment by lyusupov** [comment]
Yes, this approach looks quite appropriate.
